import type { Offer, Partner, CashoutMethod, TopEarner } from "./types";

// Avatar options for user selection
export const avatarOptions = [
  "avatar-1", "avatar-2", "avatar-3", "avatar-4", "avatar-5", "avatar-6",
  "avatar-7", "avatar-8", "avatar-9", "avatar-10", "avatar-11", "avatar-12",
  "avatar-13", "avatar-14", "avatar-15", "avatar-16", "avatar-17", "avatar-18",
  "avatar-19", "avatar-20", "avatar-21", "avatar-22", "avatar-23", "avatar-24",
  "avatar-25", "avatar-26", "avatar-27", "avatar-28", "avatar-29", "avatar-30",
];

// Mock offers data
export const mockOffers: Omit<Offer, "createdAt">[] = [
  {
    id: "1",
    partnerId: "playtime",
    partnerName: "PlayTimeAds",
    name: "Rock N' Cash Casino",
    description: "Open the app, play and reach level 10",
    image: "/images/offers/rock-n-cash.jpg",
    points: 156420,
    platforms: ["android", "ios"],
    instructions: "Install the game and reach level 10 to earn points",
    trackingUrl: "#",
    completions: 1250,
    isActive: true,
  },
  {
    id: "2",
    partnerId: "playtime",
    partnerName: "PlayTimeAds",
    name: "Wild Fish Explorer",
    description: "Open the app, play for 30 minutes",
    image: "/images/offers/wild-fish.jpg",
    points: 65901,
    platforms: ["android", "ios"],
    instructions: "Play the game for at least 30 minutes",
    trackingUrl: "#",
    completions: 980,
    isActive: true,
  },
  {
    id: "3",
    partnerId: "playtime",
    partnerName: "PlayTimeAds",
    name: "River Dash",
    description: "Open the app, complete tutorial",
    image: "/images/offers/river-dash.jpg",
    points: 59877.7,
    platforms: ["android"],
    instructions: "Complete the tutorial level",
    trackingUrl: "#",
    completions: 750,
    isActive: true,
  },
  {
    id: "4",
    partnerId: "playtime",
    partnerName: "PlayTimeAds",
    name: "River Rush",
    description: "Open the app, reach level 5",
    image: "/images/offers/river-rush.jpg",
    points: 55390.7,
    platforms: ["android", "ios"],
    instructions: "Reach level 5 in the game",
    trackingUrl: "#",
    completions: 620,
    isActive: true,
  },
  {
    id: "5",
    partnerId: "playtime",
    partnerName: "PlayTimeAds",
    name: "Tiny Garden Gnome",
    description: "Open the app, play for 20 minutes",
    image: "/images/offers/garden-gnome.jpg",
    points: 53089,
    platforms: ["android", "ios"],
    instructions: "Play for at least 20 minutes",
    trackingUrl: "#",
    completions: 540,
    isActive: true,
  },
  {
    id: "6",
    partnerId: "playtime",
    partnerName: "PlayTimeAds",
    name: "Sky Plunger",
    description: "Open the app, score 1000 points",
    image: "/images/offers/sky-plunger.jpg",
    points: 52972,
    platforms: ["android", "ios", "desktop"],
    instructions: "Score at least 1000 points in a single run",
    trackingUrl: "#",
    completions: 480,
    isActive: true,
  },
  {
    id: "7",
    partnerId: "playtime",
    partnerName: "PlayTimeAds",
    name: "Magnet Miner",
    description: "Open the app, collect 500 coins",
    image: "/images/offers/magnet-miner.jpg",
    points: 52799,
    platforms: ["android", "ios"],
    instructions: "Collect 500 coins in the game",
    trackingUrl: "#",
    completions: 420,
    isActive: true,
  },
  {
    id: "8",
    partnerId: "playtime",
    partnerName: "PlayTimeAds",
    name: "Wishing Well",
    description: "Play and reach level 3",
    image: "/images/offers/wishing-well.jpg",
    points: 52799,
    platforms: ["android"],
    instructions: "Reach level 3 in the game",
    trackingUrl: "#",
    completions: 380,
    isActive: true,
  },
  {
    id: "9",
    partnerId: "tplayad",
    partnerName: "Tplayad",
    name: "HighRoller Vegas",
    description: "Open the app, spin 50 times",
    image: "/images/offers/highroller.jpg",
    points: 39414,
    platforms: ["android", "ios"],
    instructions: "Spin the slot machine 50 times",
    trackingUrl: "#",
    completions: 350,
    isActive: true,
  },
  {
    id: "10",
    partnerId: "gemiad",
    partnerName: "GemiAd",
    name: "Jelly Jump Sprint",
    description: "Open the app, play for 15 minutes",
    image: "/images/offers/jelly-jump.jpg",
    points: 38234.7,
    platforms: ["android", "ios"],
    instructions: "Play for at least 15 minutes",
    trackingUrl: "#",
    completions: 320,
    isActive: true,
  },
  {
    id: "11",
    partnerId: "offery",
    partnerName: "Offery",
    name: "Chaos Cruiser",
    description: "Open the app, complete 5 races",
    image: "/images/offers/chaos-cruiser.jpg",
    points: 30084,
    platforms: ["android", "ios", "desktop"],
    instructions: "Complete 5 races in the game",
    trackingUrl: "#",
    completions: 290,
    isActive: true,
  },
  {
    id: "12",
    partnerId: "lootably",
    partnerName: "Lootably",
    name: "The Parachute",
    description: "Play and reach 100 meters",
    image: "/images/offers/parachute.jpg",
    points: 24971.4,
    platforms: ["android", "ios"],
    instructions: "Reach 100 meters in a single jump",
    trackingUrl: "#",
    completions: 260,
    isActive: true,
  },
  {
    id: "13",
    partnerId: "pixylabs",
    partnerName: "Pixylabs",
    name: "Pinata Fiesta",
    description: "Reach as far as possible",
    image: "/images/offers/pinata-fiesta.jpg",
    points: 24295.7,
    platforms: ["android", "desktop"],
    instructions: "Play and reach as far as you can",
    trackingUrl: "#",
    completions: 230,
    isActive: true,
  },
  {
    id: "14",
    partnerId: "pubscale",
    partnerName: "Pubscale",
    name: "Grab A Toy",
    description: "Open the app, grab 10 toys",
    image: "/images/offers/grab-toy.jpg",
    points: 21262.7,
    platforms: ["android", "ios"],
    instructions: "Grab at least 10 toys in the claw machine",
    trackingUrl: "#",
    completions: 200,
    isActive: true,
  },
  {
    id: "15",
    partnerId: "playtime",
    partnerName: "PlayTimeAds",
    name: "Treasure Hunt",
    description: "Find the hidden treasure",
    image: "/images/offers/treasure.jpg",
    points: 37,
    platforms: ["desktop"],
    instructions: "Complete the treasure hunt quiz",
    trackingUrl: "#",
    completions: 5200,
    isActive: true,
  },
  {
    id: "16",
    partnerId: "playtime",
    partnerName: "PlayTimeAds",
    name: "Mystery Chest",
    description: "Answer questions correctly",
    image: "/images/offers/mystery-chest.jpg",
    points: 34,
    platforms: ["desktop"],
    instructions: "Answer quiz questions to unlock the chest",
    trackingUrl: "#",
    completions: 4800,
    isActive: true,
  },
];

// Mock partners data
export const mockPartners: Partner[] = [
  {
    id: "playtime",
    name: "PlayTimeAds",
    logo: "/images/partners/playtime.png",
    description: "Play games and earn rewards",
    rating: 5,
    badge: "Trendify",
    badgeColor: "#f97316",
    featured: true,
    bannerImage: "/images/banners/pubscale.jpg",
    bannerTitle: "START EARN",
    bannerSubtitle: "Earn up to 250$ every day",
    isActive: true,
  },
  {
    id: "adtowall",
    name: "adtowall",
    logo: "/images/partners/adtowall.png",
    description: "Complete offers and surveys",
    rating: 5,
    badge: "TrueLeads",
    badgeColor: "#22c55e",
    featured: false,
    isActive: true,
  },
  {
    id: "gemiad",
    name: "gemiad",
    logo: "/images/partners/gemiad.png",
    description: "Gaming offers platform",
    rating: 4,
    badge: "TrustOffers",
    badgeColor: "#eab308",
    featured: false,
    isActive: true,
  },
  {
    id: "offery",
    name: "offery",
    logo: "/images/partners/offery.png",
    description: "Exclusive mobile offers",
    rating: 5,
    badge: "2X",
    badgeColor: "#3b82f6",
    featured: false,
    isActive: true,
  },
  {
    id: "lootably",
    name: "lootably",
    logo: "/images/partners/lootably.png",
    description: "Premium reward offers",
    rating: 4,
    badge: "PromoWall",
    badgeColor: "#a855f7",
    featured: false,
    isActive: true,
  },
  {
    id: "pixylabs",
    name: "pixylabs",
    logo: "/images/partners/pixylabs.png",
    description: "Game testing platform",
    rating: 3,
    badge: "PureReward",
    badgeColor: "#22c55e",
    featured: false,
    isActive: true,
  },
  {
    id: "tplayad",
    name: "tplayad",
    logo: "/images/partners/tplayad.png",
    description: "Mobile gaming rewards",
    rating: 5,
    badge: "Trendify",
    badgeColor: "#f97316",
    featured: true,
    bannerImage: "/images/banners/playtime.jpg",
    bannerTitle: "EARN UP TO 250$",
    bannerSubtitle: "SIMPLE, FAST, REAL",
    isActive: true,
  },
  {
    id: "adbreak",
    name: "adbreak",
    logo: "/images/partners/adbreak.png",
    description: "Watch ads and earn",
    rating: 4,
    badge: "RewardX",
    badgeColor: "#10b981",
    featured: false,
    isActive: true,
  },
  {
    id: "notik",
    name: "notik",
    logo: "/images/partners/notik.png",
    description: "Complete tasks for rewards",
    rating: 3,
    badge: "TrustOffers",
    badgeColor: "#eab308",
    featured: false,
    isActive: true,
  },
  {
    id: "taskwall",
    name: "taskwall",
    logo: "/images/partners/taskwall.png",
    description: "Task completion platform",
    rating: 4,
    badge: "Trendify",
    badgeColor: "#f97316",
    featured: false,
    isActive: true,
  },
  {
    id: "vortexwall",
    name: "vortexwall",
    logo: "/images/partners/vortexwall.png",
    description: "Gaming offers hub",
    rating: 3,
    badge: "PureReward",
    badgeColor: "#22c55e",
    featured: false,
    isActive: true,
  },
  {
    id: "upwall",
    name: "upwall",
    logo: "/images/partners/upwall.png",
    description: "Level up your earnings",
    rating: 3,
    badge: "RewardNova",
    badgeColor: "#f59e0b",
    featured: false,
    isActive: true,
  },
  {
    id: "farly",
    name: "Farly",
    logo: "/images/partners/farly.png",
    description: "Fair rewards platform",
    rating: 4,
    badge: "RewardX",
    badgeColor: "#10b981",
    featured: false,
    isActive: true,
  },
];

// Mock cashout methods
export const mockCashoutMethods: CashoutMethod[] = [
  // Crypto
  {
    id: "faucetpay",
    name: "faucetpay",
    logo: "/images/cashout/faucetpay.png",
    type: "crypto",
    minPoints: 100,
    conversionRate: 1000,
    isActive: true,
  },
  {
    id: "binance",
    name: "Binance",
    logo: "/images/cashout/binance.png",
    type: "crypto",
    minPoints: 500,
    conversionRate: 1000,
    isActive: true,
  },
  {
    id: "litecoin",
    name: "Litecoin",
    logo: "/images/cashout/litecoin.png",
    type: "crypto",
    minPoints: 200,
    conversionRate: 1000,
    isActive: true,
  },
  {
    id: "cwallet",
    name: "cWallet",
    logo: "/images/cashout/cwallet.png",
    type: "crypto",
    minPoints: 100,
    conversionRate: 1000,
    isActive: true,
  },
  // Cashout Methods
  {
    id: "paypal",
    name: "PayPal",
    logo: "/images/cashout/paypal.png",
    type: "cashout",
    minPoints: 1000,
    conversionRate: 1000,
    isActive: true,
  },
  {
    id: "visa",
    name: "Visa Tremendous",
    logo: "/images/cashout/visa.png",
    type: "cashout",
    minPoints: 2000,
    conversionRate: 1000,
    isActive: true,
  },
  {
    id: "egypt-cash",
    name: "Egypt Cash",
    logo: "/images/cashout/egypt-cash.png",
    type: "cashout",
    minPoints: 500,
    conversionRate: 1000,
    isActive: true,
    borderColor: "#ef4444",
  },
  {
    id: "syriatel-mtn",
    name: "Syriatel / MTN",
    logo: "/images/cashout/syriatel.png",
    type: "cashout",
    minPoints: 500,
    conversionRate: 1000,
    isActive: true,
  },
  {
    id: "syriatel-mtn-cash",
    name: "Syriatel / MTN Cash",
    logo: "/images/cashout/mtn-cash.png",
    type: "cashout",
    minPoints: 500,
    conversionRate: 1000,
    isActive: true,
  },
  {
    id: "sham-cash",
    name: "Sham cash",
    logo: "/images/cashout/sham-cash.png",
    type: "cashout",
    minPoints: 500,
    conversionRate: 1000,
    isActive: true,
  },
  // Gift Cards
  {
    id: "amazon",
    name: "Amazon",
    logo: "/images/cashout/amazon.png",
    type: "giftcard",
    minPoints: 5000,
    conversionRate: 1000,
    isActive: true,
  },
  {
    id: "google-play",
    name: "Google Play US",
    logo: "/images/cashout/google-play.png",
    type: "giftcard",
    minPoints: 5000,
    conversionRate: 1000,
    isActive: true,
  },
  {
    id: "itunes",
    name: "iTunes Apple",
    logo: "/images/cashout/itunes.png",
    type: "giftcard",
    minPoints: 5000,
    conversionRate: 1000,
    isActive: true,
  },
  {
    id: "razer-gold",
    name: "Razer Gold",
    logo: "/images/cashout/razer-gold.png",
    type: "giftcard",
    minPoints: 5000,
    conversionRate: 1000,
    isActive: true,
  },
  // Skins
  {
    id: "pubg-mobile",
    name: "PUBG Mobile",
    logo: "/images/cashout/pubg.png",
    type: "skins",
    minPoints: 3000,
    conversionRate: 1000,
    isActive: true,
  },
  {
    id: "free-fire",
    name: "Free Fire",
    logo: "/images/cashout/freefire.png",
    type: "skins",
    minPoints: 3000,
    conversionRate: 1000,
    isActive: true,
  },
];

// Mock top earners for the scrolling bar
export const mockTopEarners: TopEarner[] = [
  { id: "1", name: "mmop", avatar: "avatar-1", partnerName: "PlayTimeAds", points: 14 },
  { id: "2", name: "mmop", avatar: "avatar-2", partnerName: "PlayTimeAds", points: 21 },
  { id: "3", name: "mmop", avatar: "avatar-3", partnerName: "PlayTimeAds", points: 25 },
  { id: "4", name: "mmop", avatar: "avatar-4", partnerName: "PlayTimeAds", points: 25 },
  { id: "5", name: "mmop", avatar: "avatar-5", partnerName: "PlayTimeAds", points: 25 },
  { id: "6", name: "Mila...", avatar: "avatar-6", partnerName: "tplayad", points: 50.05 },
  { id: "7", name: "ahjf...", avatar: "avatar-7", partnerName: "pixylabs", points: 208 },
  { id: "8", name: "ahjf...", avatar: "avatar-8", partnerName: "pixylabs", points: 112 },
  { id: "9", name: "Ttt", avatar: "avatar-9", partnerName: "pubscale", points: 130 },
  { id: "10", name: "Haja", avatar: "avatar-10", partnerName: "gemiad", points: 78 },
  { id: "11", name: "Mmm", avatar: "avatar-11", partnerName: "pubscale", points: 130 },
  { id: "12", name: "Hany Ra...", avatar: "avatar-12", partnerName: "notik", points: 21.35 },
  { id: "13", name: "Yaso...", avatar: "avatar-13", partnerName: "lootably", points: 58 },
  { id: "14", name: "Mmmm...", avatar: "avatar-14", partnerName: "pubscale", points: 41.6 },
  { id: "15", name: "Ybh", avatar: "avatar-15", partnerName: "tplayad", points: 39.325 },
];
